import { FamilyAndCommunity } from "../entity/familyAndCommunity.js";
import { Documents, EducationConditionPerson, FamilyComposition, FamilyCompositionPerson, Pregnant } from "../entity/familyComposition.js";
import { FamilyComunitaryConvivation } from "../entity/familyComunitaryConvivation.js";
import { FamilyEventlyBenefits } from "../entity/familyEnvetlyBenefits.js";
import { HelphyConditionFamily } from "../entity/familyHelphyCondition.js";
import { FamilyHistoryInstitutionalComplet } from "../entity/familyHistoryInstitutionalComplet.js";
import { FamilyHistoryOfComplianceSocioEducationalMeasures } from "../entity/familyHistoryOfComplianceSocioEducationalMeasures.js";
import { FamilyHistorySocioEducation } from "../entity/familyHistorySocioEducation.js";
import { FamilyInstitucionalHistory } from "../entity/familyInstitucionalHistory.js";
import { FamilySituationViolation } from "../entity/familySituationViolation.js";
import { FirstEntryInUnity } from "../entity/firstEntryInUnity.js";
import { HelphyCondition } from "../entity/healthCondition.js";
import { HomeConditions } from "../entity/homeConditions.js";
import { Observations } from "../entity/observations.js";
import { ReferencePerson } from "../entity/referencePerson.js";
import { User } from "../entity/user.js";
import { WorkCondition } from "../entity/workCondition.js";

export interface UserRepository {
    findByEmail(email:string):Promise<any>;
    create(user:User,isAdm:boolean): Promise<User | Error>;
    delete(email:string): Promise<User | Error>;
    createReferencePerson(referencePerson:ReferencePerson): Promise<ReferencePerson | Error>;
    createReferencePersonObservation(observations:Observations,referencePersonId:string): Promise<Observations | Error>;
    listAllReferencePerson(): Promise<ReferencePerson[] | Error>;
    getByIdReferencePerson(id:string): Promise<ReferencePerson | Error>;
    getReferencePersonWithObservations(id:string): Promise<ReferencePerson | Error>;
    firstEntryInUnity(firstEntry:FirstEntryInUnity,firstEntryInUnityId:string): Promise<FirstEntryInUnity | Error>;
    getFirstEntryInUnity(firstEntryInUnityId:string): Promise<FirstEntryInUnity | Error>;
    createFirstEntryInUnityObservation(firstEntryInUnityId:string,observation:Observations): Promise<FirstEntryInUnity | Error>;
    createFamilyPerson(familyCompositionPerson:FamilyCompositionPerson,familyCompositionID:string): Promise<FamilyComposition | Error>;
    createEtnicalEspecifications(etnicalEspecifications:string,familyCompositionID:string): Promise<FamilyComposition | Error>;
    createDocuments(documents:Documents,familyCompositionID:string,id:string): Promise<FamilyComposition | Error>;
    createSocialEspecifications(socialEspecifications:string,familyCompositionID:string): Promise<FamilyComposition | Error>;
    createFamilyCompositionObservation(observation:Observations,familyCompositionID:string): Promise<FamilyComposition | Error>;
    createHomeConditions(homeConditions:HomeConditions,homeConditionsId:string): Promise<HomeConditions | Error>;
    createHomeConditionsObservation(observation:Observations,homeConditionsId:string): Promise<HomeConditions | Error>;
    createSituationViolation(situationViolation:FamilySituationViolation,familySituationId:string): Promise<FamilySituationViolation>;
    createSituationViolationObservation(situationViolationId:string,observation:Observations): Promise<FamilySituationViolation>;
    createEducationalEspecifications(educationalEspecifications:EducationConditionPerson,familySituationId:string,personId:string): Promise<FamilyComposition>;
    getFamilyCompositonPersons(familyCompositionId:string): Promise<FamilyCompositionPerson[]>;
    getInformationOfPersonAndAgeAreInSchool(familyCompositionId:string): Promise<FamilyComposition>;
    createWorkConditionObservation(workConditionId:string,observation:string): Promise<WorkCondition>;
    createHelphyCondition(HelphyCondition: HelphyCondition, helphyConditionId: string, familyHelphyCondition: HelphyConditionFamily, familyCompositionID: string, personId: string,pregnant:Pregnant): Promise<HelphyCondition>;
    createHelphyConditionObservation(helphyConditionId: string, observation: Observations): Promise<HelphyCondition>;
    createFamilyEventlyBenefits(familyEventlyBenefits:FamilyEventlyBenefits,familyEventlyBenefitsId:string): Promise<FamilyEventlyBenefits>;
    createFamilyEventlyBenefitsObservation(familyEventlyBenefitsId:string,observation:Observations): Promise<FamilyEventlyBenefits>;
    createFamilyAndCommunity(familyAndCommunity:FamilyAndCommunity,familyAndCommunityId:string): Promise<FamilyAndCommunity>;
    createFamilyAndCommunityObservation(familyAndCommunityId:string,observation:Observations): Promise<FamilyAndCommunity>;
    createFamilyComunitaryConvivationPerson(familyComunitaryConvivation:FamilyComunitaryConvivation,familyCompositionID:string,id:string): Promise<FamilyComposition>;
    createFamilyHistoryOfComplianseSocioEducationalMensure(laOrPSCInfomation:boolean, createFamilyHistoryOfComplianseSocioEducationalMensureId: string, familyHistorySocioEducation: FamilyHistorySocioEducation, familyCompositionId: string, personId: string, anotationsOfPersons: string): Promise<FamilyHistoryOfComplianceSocioEducationalMeasures>;
    createFamilyHistoryOfComplianseSocioEducationalMensureObservation(familyHistoryOfComplianseSocioEducationalMensureId:string,observation:Observations): Promise<FamilyHistoryOfComplianceSocioEducationalMeasures>;
    createFamilyHistoryInstitutionalComplets(familyHistoryInstitutionalComplet:FamilyHistoryInstitutionalComplet,familyHistoryInstitutionalCompletId:string,familuInstitucionalHistoryPerson:FamilyInstitucionalHistory,familyCompositionId:string,personId:string): Promise<FamilyHistoryInstitutionalComplet>;
    createFamilyHistoryInstitutionalCompletObservation(familyHistoryInstitutionalCompletId:string,observation:Observations): Promise<FamilyHistoryInstitutionalComplet>;
}