events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    resolver 127.0.0.11 valid=30s;

    server {
        listen 80;
        server_name localhost;

        # Aponta para o HOST (sua máquina) em vez do container
        set $backend_upstream http://host.docker.internal:3000;
        # Assumindo que o front também rode local neste cenário
        set $frontend_upstream http://host.docker.internal:3001; 

        location /health {
            proxy_pass $backend_upstream/health;
            proxy_set_header Host $host;
        }

        location /api {
            proxy_pass $backend_upstream;
            proxy_set_header Host $host;
        }

        location / {
            proxy_pass $frontend_upstream;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
        }
    }
}
