# Cenario 1: Backend rodando dentro do Docker (Container)
# Use: docker compose -f ops/docker/compose.backend-docker.yml up -d

include:
  - compose.infra.yml
  - compose.yml

services:
  backend:
    command: bun run dev
    expose:
      - "3000"
    volumes:
      - /app/node_modules
      - /app/src/modules/iam/node_modules
      - /app/src/modules/notifications/node_modules
      - /app/src/modules/shared/node_modules
      - /app/src/modules/social/node_modules

  frontend:
    command: bun run dev
    expose:
      - "3000"
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    volumes:
      - /app/node_modules
